# Generated by Django 3.2.7 on 2021-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_age_independent_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='independent',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
